Patches und Anpassungen an Testdatensätze mit verändertem Testdatentemplate
life-research/csv2fhir pull request #2
Opened 2020-11-02 17:41 UTC by fmeineke

Neu ist Split Excel und die die Ergänzung Klinische Dokumentation sowie UCUM Ergänzung gemäß KDS

2020-11-02 17:42 UTC, fmeineke commented
Nur mit diesen Anpassungen können die xlsx aus https://tmfev.sharepoint.com/:f:/s/tmf/mi-i/EvI-7k5TvGlAtZGqjaY0LOUBlGLhRZRngkrX6WoUEdQtDQ?e=kj5H3c bearbeitet werden

2020-11-02 19:43 UTC, alexanderkiel requested changes

2020-11-02 19:43 UTC, alexanderkiel commented on src/main/java/de/uni_leipzig/life/csv2fhir/Csv2Fhir.java
> -            put("Medikation (2).csv", new MedikationConverterFactory());
Kannst Du die Zeile bitte ganz entfernen. Wir werden die Medikation (2) ja nicht wieder benötigen.

2020-11-02 19:43 UTC, alexanderkiel commented on pom.xml
> +	<groupId>de.uni-leipzig.life.csv2fhir</groupId>
Wir verwenden üblicherweise keine Tabs. Es wäre schön, wenn Du das bei Dir in Eclipse anpassen könntest.

2020-11-02 19:43 UTC, alexanderkiel commented on src/main/java/de/uni_leipzig/life/csv2fhir/converter/KlinischeDokumentationConverter.java
> +            		.setSystem("http://unitsofmeasure.org").setCode("UCUM").setUnit(record.get("Einheit"));
UCUM ist keine Einheit. Wenn wir hier keine UCUM konforme Einheit haben, würde ich system und code lieber weglassen.

2020-11-02 19:43 UTC, alexanderkiel commented on src/main/java/de/uni_leipzig/life/csv2fhir/converter/LaborbefundConverter.java
> +            		.setSystem("http://unitsofmeasure.org").setCode("UCUM").setUnit(record.get("Einheit"));
Hier das Gleiche. UCUM ist keine Einheit.

2020-11-02 19:43 UTC, alexanderkiel commented on src/test/java/fmeineke/imise/de/SplitMainTest.java
> +public class SplitMainTest extends TestCase {
Entfern den manuellen Test bitte. Florian hat schon Code für ein Commandozeileninterface fertig. Damit geht das manuelle Testen auch einfach.

2020-11-04 13:53 UTC, alexanderkiel commented
Hallo Frank, soweit sieht alles gut aus. Schau aber bitte noch einmal, dass Du alle Dateien im UTF-8 Encoding speicherst. Mir zeigt IntelliJ mehrere Warnungen an und ich sehe kaputte Zeichen. Danke.

2020-11-05 11:59 UTC, alexanderkiel commented
Die CSV Dateien unter resources sind noch nicht in UTF-8.

2020-11-05 15:38 UTC, alexanderkiel approved these changes

2020-11-05 15:38 UTC, merged

2020-11-05 15:39 UTC, fmeineke commented
Sollte auch gefixed sein – ich erzeuge jetzt die Daten direkt im resource Ordner.
 
Persönlich würde auch gerne andere Dinge ändern:
 
-          logger statt System.out
-          ein detaillierterer Checkmechanismus und darauf bessere Fehlermeldungen
-          Converter als Klasse mit record
-          Dopplungen wegbekommen (Messwerte einlesen, etc)
 
Aber das geht ja über einen Patch hinaus, berührt fast alle Klassen und wäre mit Florian / dir zu besprechen?
 
Anbei die Dokumente die ich Herrn Schepers geschickt habe.
 
Bekommst Du denn immer Nachricht, wenn ich den Push HEAD klicke?
 
Gruß, Frank 
 
Von: Alexander Kiel <notifications@github.com> 
Gesendet: Donnerstag, 5. November 2020 13:00
An: life-research/csv2fhir <csv2fhir@noreply.github.com>
Cc: fmeineke <frank.meineke@imise.uni-leipzig.de>; Author <author@noreply.github.com>
Betreff: Re: [life-research/csv2fhir] Patches und Anpassungen an Testdatensätze mit verändertem Testdatentemplate (#2)
 
Die CSV Dateien unter resources sind noch nicht in UTF-8.
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub https://github.com/life-research/csv2fhir/pull/2#issuecomment-722333633, or unsubscribe https://github.com/notifications/unsubscribe-auth/AENL7TKZUGSON7PAE4LAWJTSOKHSLANCNFSM4THYK3VA.